theme: null
title: De Onwijze Wijsheden
description: Tussen onzin en openbaring
baseurl: "/Crackthecode"   # alleen als je repo Crackthecode heet (check!)
url: "https://littlepasha1.github.io/Crackthecode/"  # vervang met je echte gebruikersnaam
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
